# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            vance's blog
description:      '保持简单'
url:              https://vancefantasy.github.io
baseurl:          

author:
  name:           'vancefantasy'
  url:            https://vancefantasy.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vancefantasy/vancefantasy.github.io
